# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
    matrix:
      #Python27:
      #  python.version: '2.7'
      #Python36:
      #  python.version: '3.6'
      Python37:
        python.version: '3.7'

variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.pip
  AZURE_TEST: 1

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
  
- task: Cache@2
  inputs:
    key: 'python | "$(Agent.OS)" | requirements.txt'
    restoreKeys: | 
      python | "$(Agent.OS)"
      python
    path: $(PIP_CACHE_DIR)
  displayName: Cache pip packages

- script: |
    python -m pip install --upgrade pip
    pip install -r test_requirements.txt
    # pip install git+https://github.com/olivierverdier/dispatch.git
    # pip install git+https://github.com/python-microscopy/pymecompress
    pip install wheel
    pip install --no-build-isolation pymecompress
    pip install 'pytest<=5.3.2' pytest-azurepipelines pytest-cov pytest-html flake8 diff-cover
  displayName: 'Install dependencies'

- script: |
    python setup.py develop
  displayName: 'build'

- script: |
    #cd tests
    pytest -v --html=report.html tests/ --cov PYME --cov-report xml
  displayName: 'pytest'
  
- script: |
    #cd tests
    #bash <(curl -s https://codecov.io/bash)
    curl -Os https://uploader.codecov.io/latest/linux/codecov 
    chmod +x codecov
    #./codecov -f coverage.xml -F all -F core -C $(Build.SourceVersion)
    ./codecov -f coverage.xml -F all -F core
  condition: and(succeededOrFailed(), eq(variables['python.version'], '3.7'))
  displayName: 'codecov upload'
  env:
    CODECOV_TOKEN: $(CODECOV_T)
  
# - script: |
#     diff-cover coverage.xml --compare-branch=master 
#   condition: succeededOrFailed()
#   displayName: 'diff-cover'

# - script: |
#     diff-quality --violations=flake8 --compare-branch=master
#   condition: succeededOrFailed()
#   displayName: 'diff-quality'
